"""Message model for chatbot conversations."""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, UUIDMixin

if TYPE_CHECKING:
    from app.models.conversation import Conversation


class Message(Base, UUIDMixin):
    """A single message in a conversation."""

    __tablename__ = "messages"

    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    intent: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    intent_confidence: Mapped[Decimal | None] = mapped_column(Numeric(3, 2), nullable=True)
    llm_provider: Mapped[str | None] = mapped_column(String(50), nullable=True)
    llm_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    tokens_used: Mapped[int | None] = mapped_column(Integer, nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    retrieved_documents: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB, nullable=True)
    feedback_score: Mapped[int | None] = mapped_column(Integer, nullable=True)
    flagged_for_review: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    reviewed_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True,
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    review_action: Mapped[str | None] = mapped_column(String(20), nullable=True)
    corrected_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    conversation: Mapped[Conversation] = relationship("Conversation", back_populates="messages")

    def is_from_user(self) -> bool:
        """Return whether the message was sent by a customer."""
        return self.role == "user"

    def is_from_bot(self) -> bool:
        """Return whether the message was generated by the assistant."""
        return self.role == "assistant"

    def is_from_staff(self) -> bool:
        """Return whether the message was sent by staff."""
        return self.role == "staff"

    def should_be_flagged(self) -> bool:
        """Return whether feedback or low confidence requires staff review."""
        if self.feedback_score == -1:
            return True
        if self.intent_confidence is None:
            return False
        return float(self.intent_confidence) < 0.6
