"""Knowledge base schemas."""

from datetime import datetime
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field

KnowledgeCategory = Literal[
    "safety",
    "product_info",
    "delivery",
    "pricing",
    "company",
    "faq",
    "technical",
]


class KnowledgeBaseBase(BaseModel):
    """Shared knowledge base fields."""

    title: str = Field(min_length=1, max_length=255)
    content: str = Field(min_length=1)
    category: KnowledgeCategory
    source: str | None = Field(default=None, max_length=255)
    metadata: dict[str, Any] = Field(default_factory=dict)


class KnowledgeBaseCreate(KnowledgeBaseBase):
    """Create payload. Embeddings are generated by the service."""


class KnowledgeBaseUpdate(BaseModel):
    """Update payload. All fields are optional."""

    title: str | None = Field(default=None, min_length=1, max_length=255)
    content: str | None = Field(default=None, min_length=1)
    category: KnowledgeCategory | None = None
    source: str | None = Field(default=None, max_length=255)
    metadata: dict[str, Any] | None = None
    is_active: bool | None = None


class KnowledgeBaseResponse(KnowledgeBaseBase):
    """Knowledge base response without embedding vectors."""

    id: UUID
    is_active: bool
    created_at: datetime
    updated_at: datetime


class KnowledgeBaseSearchRequest(BaseModel):
    """Search request for RAG retrieval testing."""

    query: str = Field(min_length=1, max_length=1000)
    top_k: int = Field(default=5, ge=1, le=20)
    category: KnowledgeCategory | None = None
    use_hybrid: bool = True


class KnowledgeBaseSearchResult(BaseModel):
    """Search result without embedding vectors."""

    id: UUID
    title: str
    content: str
    category: str
    similarity: float
    source: str | None = None


class KnowledgeBaseListResponse(BaseModel):
    """Paginated knowledge base list response."""

    items: list[KnowledgeBaseResponse]
    total: int
    page: int
    limit: int
    has_more: bool


class KnowledgeBaseImportResponse(BaseModel):
    """Bulk import summary."""

    count: int
    errors: list[str]


class KnowledgeBaseStatistics(BaseModel):
    """Knowledge base aggregate statistics."""

    total: int
    active: int
    by_category: dict[str, int]
    recent_additions: int
